version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/project

jobs:
  build:
    # docker:
    #   - image: circleci/node:13.8.0
    <<: *defaults
    steps:
      - checkout
      - run: npm  run lint
  test:
    # docker:
    #   - image: circleci/node:13.8.0
    <<: *defaults
    steps:
      - checkout
      - run: npm  run test
  analyze:
    # docker:
    #   - image: circleci/node:13.8.0
    <<: *defaults
    steps:
      - checkout
      - run: npm  run audit
